/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  User,
  UserLogin,
  UserOutput,
  UserRegister,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    UserFromJSON,
    UserToJSON,
    UserLoginFromJSON,
    UserLoginToJSON,
    UserOutputFromJSON,
    UserOutputToJSON,
    UserRegisterFromJSON,
    UserRegisterToJSON,
} from '../models/index';

export interface LoginRequest {
    userLogin: UserLogin;
}

export interface RegisterRequest {
    userRegister: UserRegister;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Login a user.
     * Login an existing user and get a JWT token.
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOutput>> {
        if (requestParameters['userLogin'] == null) {
            throw new runtime.RequiredError(
                'userLogin',
                'Required parameter "userLogin" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';
        headerParameters['Access-Control-Allow-Origin'] = '*';
        

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginToJSON(requestParameters['userLogin']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserOutputFromJSON(jsonValue));
    }

    /**
     * Login a user.
     * Login an existing user and get a JWT token.
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOutput> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new user with CUSTOMER role.
     * Register a new user.
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userRegister'] == null) {
            throw new runtime.RequiredError(
                'userRegister',
                'Required parameter "userRegister" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterToJSON(requestParameters['userRegister']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Register a new user with CUSTOMER role.
     * Register a new user.
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

  
  export function getToken(): string | null {
    return localStorage.getItem('token')
  }
  
  export function removeToken() {
    localStorage.removeItem('token')
  }
