/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CartWithItems,
  ErrorModel,
} from '../models/index';
import {
    CartWithItemsFromJSON,
    CartWithItemsToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index';

/**
 * 
 */
export class CartApi extends runtime.BaseAPI {

    /**
     * Removes all items in user\'s cart.
     * Deletes logged user\'s cart.
     */
    async deleteCartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/cart`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes all items in user\'s cart.
     * Deletes logged user\'s cart.
     */
    async deleteCart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCartRaw(initOverrides);
    }

    /**
     * Retrieves logged user\'s cart items.
     * Retrieves logged user\'s cart.
     */
    async getCartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartWithItems>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/cart`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartWithItemsFromJSON(jsonValue));
    }

    /**
     * Retrieves logged user\'s cart items.
     * Retrieves logged user\'s cart.
     */
    async getCart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartWithItems> {
        const response = await this.getCartRaw(initOverrides);
        return await response.value();
    }

}
