/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddItemToCartRequest,
  CartWithItems,
  ErrorModel,
  UpdateCartItemQuantityRequest,
} from '../models/index';
import {
    AddItemToCartRequestFromJSON,
    AddItemToCartRequestToJSON,
    CartWithItemsFromJSON,
    CartWithItemsToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    UpdateCartItemQuantityRequestFromJSON,
    UpdateCartItemQuantityRequestToJSON,
} from '../models/index';

export interface AddCartItemRequest {
    addItemToCartRequest: AddItemToCartRequest;
}

export interface DeleteCartItemRequest {
    cartItemId: number;
}

export interface UpdateCartItemRequest {
    cartItemId: number;
    updateCartItemQuantityRequest: UpdateCartItemQuantityRequest;
}

/**
 * 
 */
export class CartItemsApi extends runtime.BaseAPI {

    /**
     * Adds an item and quantity to the cart.
     * Adds an item to logged user\'s cart.
     */
    async addCartItemRaw(requestParameters: AddCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartWithItems>> {
        if (requestParameters['addItemToCartRequest'] == null) {
            throw new runtime.RequiredError(
                'addItemToCartRequest',
                'Required parameter "addItemToCartRequest" was null or undefined when calling addCartItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/cart/items`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddItemToCartRequestToJSON(requestParameters['addItemToCartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartWithItemsFromJSON(jsonValue));
    }

    /**
     * Adds an item and quantity to the cart.
     * Adds an item to logged user\'s cart.
     */
    async addCartItem(requestParameters: AddCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartWithItems> {
        const response = await this.addCartItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an item from logged user\'s cart.
     * Deletes an item from logged user\'s cart.
     */
    async deleteCartItemRaw(requestParameters: DeleteCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cartItemId'] == null) {
            throw new runtime.RequiredError(
                'cartItemId',
                'Required parameter "cartItemId" was null or undefined when calling deleteCartItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/cart/items/{cartItemId}`.replace(`{${"cartItemId"}}`, encodeURIComponent(String(requestParameters['cartItemId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an item from logged user\'s cart.
     * Deletes an item from logged user\'s cart.
     */
    async deleteCartItem(requestParameters: DeleteCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCartItemRaw(requestParameters, initOverrides);
    }

    /**
     * Updates item\'s quantity in logged user\'s cart.
     * Updates item\'s quantity in logged user\'s cart.
     */
    async updateCartItemRaw(requestParameters: UpdateCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartWithItems>> {
        if (requestParameters['cartItemId'] == null) {
            throw new runtime.RequiredError(
                'cartItemId',
                'Required parameter "cartItemId" was null or undefined when calling updateCartItem().'
            );
        }

        if (requestParameters['updateCartItemQuantityRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCartItemQuantityRequest',
                'Required parameter "updateCartItemQuantityRequest" was null or undefined when calling updateCartItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/cart/items/{cartItemId}`.replace(`{${"cartItemId"}}`, encodeURIComponent(String(requestParameters['cartItemId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCartItemQuantityRequestToJSON(requestParameters['updateCartItemQuantityRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartWithItemsFromJSON(jsonValue));
    }

    /**
     * Updates item\'s quantity in logged user\'s cart.
     * Updates item\'s quantity in logged user\'s cart.
     */
    async updateCartItem(requestParameters: UpdateCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartWithItems> {
        const response = await this.updateCartItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
