/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrderRequest,
  ErrorModel,
  Order,
  OrderWithItems,
  UpdateOrderStatusRequest,
} from '../models/index';
import {
    CreateOrderRequestFromJSON,
    CreateOrderRequestToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    OrderFromJSON,
    OrderToJSON,
    OrderWithItemsFromJSON,
    OrderWithItemsToJSON,
    UpdateOrderStatusRequestFromJSON,
    UpdateOrderStatusRequestToJSON,
} from '../models/index';

export interface AddOrderRequest {
    createOrderRequest: CreateOrderRequest;
}

export interface GetOrderByIdRequest {
    orderId: number;
}

export interface UpdateOrderStatusOperationRequest {
    orderId: number;
    updateOrderStatusRequest: UpdateOrderStatusRequest;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Places a new order form logged user\'s cart. Deletes the cart after creation.
     * Places a new order form logged user\'s cart.
     */
    async addOrderRaw(requestParameters: AddOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderWithItems>> {
        if (requestParameters['createOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrderRequest',
                'Required parameter "createOrderRequest" was null or undefined when calling addOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/order`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrderRequestToJSON(requestParameters['createOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderWithItemsFromJSON(jsonValue));
    }

    /**
     * Places a new order form logged user\'s cart. Deletes the cart after creation.
     * Places a new order form logged user\'s cart.
     */
    async addOrder(requestParameters: AddOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderWithItems> {
        const response = await this.addOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all logged user\'s orders.
     * Retrieves all logged user\'s orders.
     */
    async getAllOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Order>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/order`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderFromJSON));
    }

    /**
     * Retrieves all logged user\'s orders.
     * Retrieves all logged user\'s orders.
     */
    async getAllOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Order>> {
        const response = await this.getAllOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Allows admins to see the status of all orders
     * Retrieves all users orders (Admin only).
     */
    async getAllUsersOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Order>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/order/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderFromJSON));
    }

    /**
     * Allows admins to see the status of all orders
     * Retrieves all users orders (Admin only).
     */
    async getAllUsersOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Order>> {
        const response = await this.getAllUsersOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieves an order by ID, giving that it belongs to the logged user.
     * Retrieves a specific logged user\'s order.
     */
    async getOrderByIdRaw(requestParameters: GetOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderWithItems>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getOrderById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/order/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderWithItemsFromJSON(jsonValue));
    }

    /**
     * Retrieves an order by ID, giving that it belongs to the logged user.
     * Retrieves a specific logged user\'s order.
     */
    async getOrderById(requestParameters: GetOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderWithItems> {
        const response = await this.getOrderByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allows admins to update the status of a specific order
     * Updates order status (Admin only).
     */
    async updateOrderStatusRaw(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling updateOrderStatus().'
            );
        }

        if (requestParameters['updateOrderStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrderStatusRequest',
                'Required parameter "updateOrderStatusRequest" was null or undefined when calling updateOrderStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/order/{orderId}/status`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrderStatusRequestToJSON(requestParameters['updateOrderStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Allows admins to update the status of a specific order
     * Updates order status (Admin only).
     */
    async updateOrderStatus(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.updateOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
