/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Category,
  ErrorModel,
  ProductOutput,
  ProductPrice,
  ProductQuantity,
} from '../models/index';
import {
    CategoryFromJSON,
    CategoryToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    ProductOutputFromJSON,
    ProductOutputToJSON,
    ProductPriceFromJSON,
    ProductPriceToJSON,
    ProductQuantityFromJSON,
    ProductQuantityToJSON,
} from '../models/index';

export interface AddProductRequest {
    title: string;
    pDescription: string;
    category: Category;
    price: ProductPrice;
    quantity: ProductQuantity;
    image?: Blob;
}

export interface DeleteProductRequest {
    productId: number;
}

export interface FindProductByIdRequest {
    productId: number;
}

export interface UpdateProductRequest {
    productId: number;
    title: string;
    pDescription: string;
    category: Category;
    price: ProductPrice;
    quantity: ProductQuantity;
    image?: Blob;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     * Add a new product to the store, including image.
     * Add a new product to the store.
     */
    async addProductRaw(requestParameters: AddProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOutput>> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling addProduct().'
            );
        }

        if (requestParameters['pDescription'] == null) {
            throw new runtime.RequiredError(
                'pDescription',
                'Required parameter "pDescription" was null or undefined when calling addProduct().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling addProduct().'
            );
        }

        if (requestParameters['price'] == null) {
            throw new runtime.RequiredError(
                'price',
                'Required parameter "price" was null or undefined when calling addProduct().'
            );
        }

        if (requestParameters['quantity'] == null) {
            throw new runtime.RequiredError(
                'quantity',
                'Required parameter "quantity" was null or undefined when calling addProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['image'] != null) {
            formParams.append('image', requestParameters['image'] as any);
        }

        if (requestParameters['title'] != null) {
            formParams.append('title', requestParameters['title'] as any);
        }

        if (requestParameters['pDescription'] != null) {
            formParams.append('pDescription', requestParameters['pDescription'] as any);
        }

        if (requestParameters['category'] != null) {
            formParams.append('category', requestParameters['category'] as any);
        }

        if (requestParameters['price'] != null) {
            formParams.append('price', new Blob([JSON.stringify(ProductOutputToJSON(requestParameters['price']))], { type: "application/json", }));
                    }

        if (requestParameters['quantity'] != null) {
            formParams.append('quantity', new Blob([JSON.stringify(ProductOutputToJSON(requestParameters['quantity']))], { type: "application/json", }));
                    }

        const response = await this.request({
            path: `/product`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductOutputFromJSON(jsonValue));
    }

    /**
     * Add a new product to the store, including image.
     * Add a new product to the store.
     */
    async addProduct(requestParameters: AddProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOutput> {
        const response = await this.addProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a product.
     * Deletes a product.
     */
    async deleteProductRaw(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling deleteProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/product/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a product.
     * Deletes a product.
     */
    async deleteProduct(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductRaw(requestParameters, initOverrides);
    }

    /**
     * Finds all products in the store.
     * Finds all products in the store.
     */
    async findAllProductsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductOutput>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/product`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductOutputFromJSON));
    }

    /**
     * Finds all products in the store.
     * Finds all products in the store.
     */
    async findAllProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductOutput>> {
        const response = await this.findAllProductsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a single product.
     * Finds product by ID.
     */
    async findProductByIdRaw(requestParameters: FindProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling findProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/product/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductOutputFromJSON(jsonValue));
    }

    /**
     * Returns a single product.
     * Finds product by ID.
     */
    async findProductById(requestParameters: FindProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOutput> {
        const response = await this.findProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing product by ID.
     * Update an existing product.
     */
    async updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['pDescription'] == null) {
            throw new runtime.RequiredError(
                'pDescription',
                'Required parameter "pDescription" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['price'] == null) {
            throw new runtime.RequiredError(
                'price',
                'Required parameter "price" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['quantity'] == null) {
            throw new runtime.RequiredError(
                'quantity',
                'Required parameter "quantity" was null or undefined when calling updateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['image'] != null) {
            formParams.append('image', requestParameters['image'] as any);
        }

        if (requestParameters['title'] != null) {
            formParams.append('title', requestParameters['title'] as any);
        }

        if (requestParameters['pDescription'] != null) {
            formParams.append('pDescription', requestParameters['pDescription'] as any);
        }

        if (requestParameters['category'] != null) {
            formParams.append('category', requestParameters['category'] as any);
        }

        if (requestParameters['price'] != null) {
            formParams.append('price', new Blob([JSON.stringify(ProductOutputToJSON(requestParameters['price']))], { type: "application/json", }));
                    }

        if (requestParameters['quantity'] != null) {
            formParams.append('quantity', new Blob([JSON.stringify(ProductOutputToJSON(requestParameters['quantity']))], { type: "application/json", }));
                    }

        const response = await this.request({
            path: `/product/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductOutputFromJSON(jsonValue));
    }

    /**
     * Update an existing product by ID.
     * Update an existing product.
     */
    async updateProduct(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOutput> {
        const response = await this.updateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
