components:
  schemas:
    Product:
      description: Product Model
      type: object
      required:
        - title
        - pDescription
        - category
        - price
        - quantity
      properties:
        title:
          type: string
          example: Penna
        pDescription:
          type: string
          example: Penna multicolore BIC
        category:
          $ref: '#/components/schemas/Category'
        price:
          oneOf:
            - type: string
            - type: number
              format: float
          example: 9.99
        quantity:
          oneOf:
            - type: string
            - type: integer
          example: 10

    ProductInput:
      description: Product Model Input
      type: object
      allOf:
        - $ref: '#/components/schemas/Product'
      properties:
        image:
          type: string
          format: binary
          description: Image file for the product

    ProductOutput:
      description: Product Model Output
      type: object
      required:
        - id
        - imageUrl
      allOf:
        - $ref: '#/components/schemas/Product'
      properties:
        id:
          type: number
          example: 0
        imageUrl:
          type: string
          description: Image path for the product
