/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint for Shop API */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds all products in the store.
         * @description Finds all products in the store.
         */
        get: operations["findAllProducts"];
        /**
         * Update an existing product.
         * @description Update an existing product by ID.
         */
        put: operations["updateProduct"];
        /**
         * Add a new product to the store.
         * @description Add a new product to the store.
         */
        post: operations["addProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds product by ID.
         * @description Returns a single product.
         */
        get: operations["findProductById"];
        put?: never;
        post?: never;
        /**
         * Deletes a product.
         * @description Delete a product.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Category Model
         * @enum {string}
         */
        Category: "ORTOFRUTTA" | "SURGELATI" | "BANCO";
        ErrorModel: {
            message: string;
        };
        /** @description Health check status */
        HealthStatus: {
            /** @enum {string} */
            status: "OK";
            /**
             * @description Number of milliseconds since Epoch time
             * @example 1688612539479
             */
            timestamp: number;
        };
        /** @description Product Model */
        Product: {
            /**
             * Format: int64
             * @example 0
             */
            id?: number;
            /** @example Penna */
            title: string;
            /** @example Penna multicolore BIC */
            pDescription: string;
            category: components["schemas"]["Category"];
            /**
             * Format: double
             * @example 9.99
             */
            price: number;
            /**
             * Format: int64
             * @example 10
             */
            quantity: number;
            /** @example https://localohost:8080/img/img1.jpg */
            imageUrl?: string;
        };
        /** @description User Model */
        User: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example theUser */
            username: string;
            /** @example John */
            firstName: string;
            /** @example James */
            lastName: string;
            /** @example john@email.com */
            email: string;
            /** @example Password1! */
            password: string;
            /** @example 12345 */
            phone?: string;
            /** @example via Roma, 1 - Roma */
            address: string;
            userRole?: components["schemas"]["UserRole"];
        };
        /**
         * @description User Role Model
         * @enum {string}
         */
        UserRole: "CUSTOMER" | "EMPLOYEE" | "ADMIN";
    };
    responses: {
        /** @description Internal server error (500) */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Bad request error (400) */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Not found error (404) */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Unprocessable entity error (422) */
        UnprocessableEntityError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    findAllProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update an existing product in the store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    addProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new product in the store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Invalid input */
            400: components["responses"]["BadRequestError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    findProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to return */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to delete */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
}
