/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user.
         * @description Register a new user with CUSTOMER role.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login an existing user and get a JWT token.
         * @description Login a user.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves logged user's cart.
         * @description Retrieves logged user's cart items.
         */
        get: operations["getCart"];
        put?: never;
        post?: never;
        /**
         * Deletes logged user's cart.
         * @description Removes all items in user's cart.
         */
        delete: operations["deleteCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adds an item to logged user's cart.
         * @description Adds an item and quantity to the cart.
         */
        post: operations["addCartItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{cartItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Updates item's quantity in logged user's cart.
         * @description Updates item's quantity in logged user's cart.
         */
        put: operations["updateCartItem"];
        post?: never;
        /**
         * Deletes an item from logged user's cart.
         * @description Deletes an item from logged user's cart.
         */
        delete: operations["deleteCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint for Shop API */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds all products in the store.
         * @description Finds all products in the store.
         */
        get: operations["findAllProducts"];
        put?: never;
        /**
         * Add a new product to the store.
         * @description Add a new product to the store, including image.
         */
        post: operations["addProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds product by ID.
         * @description Returns a single product.
         */
        get: operations["findProductById"];
        /**
         * Update an existing product.
         * @description Update an existing product by ID.
         */
        put: operations["updateProduct"];
        post?: never;
        /**
         * Deletes a product.
         * @description Delete a product.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds all users in the store.
         * @description Finds all users in the store.
         */
        get: operations["findAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds user by ID.
         * @description Returns a single user.
         */
        get: operations["findUserById"];
        /**
         * Update an existing user.
         * @description Update an existing user by ID.
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Deletes a user.
         * @description Delete a user.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CartWithItems: {
            /** @description ID univoco del carrello. */
            readonly id?: number;
            /** @description ID dell'utente a cui appartiene il carrello. */
            readonly UserId: number;
            cartItems?: components["schemas"]["CartItem"][];
        };
        CartItem: {
            /** @description ID univoco dell'elemento del carrello. */
            readonly id?: number;
            /** @description ID del carrello a cui appartiene l'elemento. */
            readonly CartId?: number;
            /** @description ID del prodotto nell'elemento del carrello. */
            ProductId: number;
            /** @description Quantità del prodotto nell'elemento del carrello. */
            quantity: number;
        };
        AddItemToCartRequest: {
            /** @description ID del prodotto da aggiungere. */
            ProductId: number;
            /** @description Quantità da aggiungere. */
            quantity: number;
        };
        UpdateCartItemQuantityRequest: {
            /** @description Nuova quantità. */
            quantity: number;
        };
        /**
         * @description Category Model
         * @enum {string}
         */
        Category: "ORTOFRUTTA" | "SURGELATI" | "BANCO" | "ELETTRONICA" | "CASA" | "SURGELATI" | "LIQUORI";
        ErrorModel: {
            message: string;
        };
        /** @description Health check status */
        HealthStatus: {
            /** @enum {string} */
            status: "OK";
            /**
             * @description Number of milliseconds since Epoch time
             * @example 1688612539479
             */
            timestamp: number;
        };
        /** @description Product Model */
        Product: {
            /** @example Penna */
            title: string;
            /** @example Penna multicolore BIC */
            pDescription: string;
            category: components["schemas"]["Category"];
            /** @example 9.99 */
            price: string;
            /** @example 10 */
            quantity: string;
        };
        /** @description Product Model Input */
        ProductInput: {
            /**
             * Format: binary
             * @description Image file for the product
             */
            image?: string;
        } & components["schemas"]["Product"];
        /** @description Product Model Output */
        ProductOutput: {
            /** @example 0 */
            id: number;
            /** @description Image path for the product */
            imageUrl: string;
        } & components["schemas"]["Product"];
        /** @description User Model */
        User: {
            /** @example 1 */
            username: string;
            /** @example John */
            firstName: string;
            /** @example James */
            lastName: string;
            /** @example test@example.com */
            email: string;
            /** @example 12345 */
            phone?: string;
            /** @example via Roma, 1 - Roma */
            address: string;
        };
        /** @description User Model Input */
        UserInput: {
            /** @example Password1! */
            password: string;
            userRole?: components["schemas"]["UserRole"];
        } & components["schemas"]["User"];
        /** @description User Model Output */
        UserOutput: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example token */
            token?: string;
        } & components["schemas"]["User"];
        /** @description User Model for registration */
        UserRegister: {
            /** @example Password1! */
            password: string;
        } & components["schemas"]["User"];
        /** @description User Login Model */
        UserLogin: {
            /** @example 1 */
            username?: string;
            /** @example test@example.com */
            email?: string;
            /** @example Password1! */
            password: string;
        };
        /**
         * @description User Role Model
         * @enum {string}
         */
        UserRole: "CUSTOMER" | "EMPLOYEE" | "ADMIN";
    };
    responses: {
        /** @description Bad request error (400) */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Invalid credentials error (401) */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Invalid credentials error (403) */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Not found error (404) */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Unprocessable entity error (422) */
        UnprocessableEntityError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Internal server error (500) */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new user */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequestError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login an existing user */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description User logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartWithItems"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemToCartRequest"];
            };
        };
        responses: {
            /** @description Item added successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartWithItems"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID dell'elemento del carrello da aggiornare. */
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemQuantityRequest"];
            };
        };
        responses: {
            /** @description Item quantity successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartWithItems"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID dell'elemento del carrello da rimuovere. */
                cartItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    findAllProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new product in the store */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    findProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to return */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            400: components["responses"]["BadRequestError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to return */
                productId: number;
            };
            cookie?: never;
        };
        /** @description Update an existing product in the store */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to delete */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    findAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    findUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of user to return */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of user to update */
                userId: number;
            };
            cookie?: never;
        };
        /** @description Update an existing user in the store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["UnprocessableEntityError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of user to delete */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
