/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint for Shop API */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds all products in the store.
         * @description Finds all products in the store.
         */
        get: operations["findAllProducts"];
        put?: never;
        /**
         * Add a new product to the store.
         * @description Add a new product to the store, including image.
         */
        post: operations["addProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds product by ID.
         * @description Returns a single product.
         */
        get: operations["findProductById"];
        /**
         * Update an existing product.
         * @description Update an existing product by ID.
         */
        put: operations["updateProduct"];
        post?: never;
        /**
         * Deletes a product.
         * @description Delete a product.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds all users in the store.
         * @description Finds all users in the store.
         */
        get: operations["findAllUsers"];
        /**
         * Update an existing user.
         * @description Update an existing user by ID.
         */
        put: operations["updateUser"];
        /**
         * Add a new user.
         * @description Add a new user with CUSTOMER role.
         */
        post: operations["addUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finds user by ID.
         * @description Returns a single user.
         */
        get: operations["findUserById"];
        put?: never;
        post?: never;
        /**
         * Deletes a user.
         * @description Delete a user.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Category Model
         * @enum {string}
         */
        Category: "ORTOFRUTTA" | "SURGELATI" | "BANCO";
        ErrorModel: {
            message: string;
        };
        /** @description Health check status */
        HealthStatus: {
            /** @enum {string} */
            status: "OK";
            /**
             * @description Number of milliseconds since Epoch time
             * @example 1688612539479
             */
            timestamp: number;
        };
        /** @description Product Model */
        Product: {
            /** @example Penna */
            title: string;
            /** @example Penna multicolore BIC */
            pDescription: string;
            category: components["schemas"]["Category"];
            /** @example 9.99 */
            price: string;
            /** @example 10 */
            quantity: string;
        };
        /** @description Product Model Input */
        ProductInput: {
            /**
             * Format: binary
             * @description Image file for the product
             */
            image?: string;
        } & components["schemas"]["Product"];
        /** @description Product Model Output */
        ProductOutput: {
            /** @example 0 */
            id: number;
            /** @description Image path for the product */
            imageUrl: string;
        } & components["schemas"]["Product"];
        /** @description User Model */
        User: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example theUser */
            username: string;
            /** @example John */
            firstName: string;
            /** @example James */
            lastName: string;
            /** @example john@email.com */
            email: string;
            /** @example Password1! */
            password: string;
            /** @example 12345 */
            phone?: string;
            /** @example via Roma, 1 - Roma */
            address: string;
            userRole?: components["schemas"]["UserRole"];
        };
        /**
         * @description User Role Model
         * @enum {string}
         */
        UserRole: "CUSTOMER" | "EMPLOYEE" | "ADMIN";
    };
    responses: {
        /** @description Internal server error (500) */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Bad request error (400) */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Not found error (404) */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Unprocessable entity error (422) */
        UnprocessableEntityError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    findAllProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"][];
                };
            };
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    addProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new product in the store */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            /** @description Invalid input */
            400: components["responses"]["BadRequestError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    findProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to return */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update an existing product in the store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of product to delete */
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description Product not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    findAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update an existing user in the store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description User not found */
            404: components["responses"]["NotFoundError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    addUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new user */
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid input */
            400: components["responses"]["BadRequestError"];
            /** @description Validation exception */
            422: components["responses"]["UnprocessableEntityError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    findUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of user to return */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description User not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of user to delete */
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid ID supplied */
            400: components["responses"]["BadRequestError"];
            /** @description User not found */
            404: components["responses"]["NotFoundError"];
            /** @description Unexpected server error */
            500: components["responses"]["InternalServerError"];
        };
    };
}
