/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddItemToCartRequest
 */
export interface AddItemToCartRequest {
    /**
     * ID del prodotto da aggiungere.
     * @type {number}
     * @memberof AddItemToCartRequest
     */
    productId: number;
    /**
     * Quantità da aggiungere.
     * @type {number}
     * @memberof AddItemToCartRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the AddItemToCartRequest interface.
 */
export function instanceOfAddItemToCartRequest(value: object): value is AddItemToCartRequest {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function AddItemToCartRequestFromJSON(json: any): AddItemToCartRequest {
    return AddItemToCartRequestFromJSONTyped(json, false);
}

export function AddItemToCartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddItemToCartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['ProductId'],
        'quantity': json['quantity'],
    };
}

export function AddItemToCartRequestToJSON(json: any): AddItemToCartRequest {
    return AddItemToCartRequestToJSONTyped(json, false);
}

export function AddItemToCartRequestToJSONTyped(value?: AddItemToCartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProductId': value['productId'],
        'quantity': value['quantity'],
    };
}

