/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
    /**
     * ID univoco dell'elemento del carrello.
     * @type {number}
     * @memberof CartItem
     */
    readonly id?: number;
    /**
     * ID del carrello a cui appartiene l'elemento.
     * @type {number}
     * @memberof CartItem
     */
    readonly cartId?: number;
    /**
     * ID del prodotto nell'elemento del carrello.
     * @type {number}
     * @memberof CartItem
     */
    productId: number;
    /**
     * Quantità del prodotto nell'elemento del carrello.
     * @type {number}
     * @memberof CartItem
     */
    quantity: number;
}

/**
 * Check if a given object implements the CartItem interface.
 */
export function instanceOfCartItem(value: object): value is CartItem {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemFromJSON(json: any): CartItem {
    return CartItemFromJSONTyped(json, false);
}

export function CartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'cartId': json['CartId'] == null ? undefined : json['CartId'],
        'productId': json['ProductId'],
        'quantity': json['quantity'],
    };
}

export function CartItemToJSON(json: any): CartItem {
    return CartItemToJSONTyped(json, false);
}

export function CartItemToJSONTyped(value?: Omit<CartItem, 'id'|'CartId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProductId': value['productId'],
        'quantity': value['quantity'],
    };
}

