/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
    CartItemToJSONTyped,
} from './CartItem';

/**
 * 
 * @export
 * @interface CartWithItems
 */
export interface CartWithItems {
    /**
     * ID univoco del carrello.
     * @type {number}
     * @memberof CartWithItems
     */
    readonly id?: number;
    /**
     * ID dell'utente a cui appartiene il carrello.
     * @type {number}
     * @memberof CartWithItems
     */
    readonly userId: number;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof CartWithItems
     */
    cartItems?: Array<CartItem>;
}

/**
 * Check if a given object implements the CartWithItems interface.
 */
export function instanceOfCartWithItems(value: object): value is CartWithItems {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CartWithItemsFromJSON(json: any): CartWithItems {
    return CartWithItemsFromJSONTyped(json, false);
}

export function CartWithItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartWithItems {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['UserId'],
        'cartItems': json['cartItems'] == null ? undefined : ((json['cartItems'] as Array<any>).map(CartItemFromJSON)),
    };
}

export function CartWithItemsToJSON(json: any): CartWithItems {
    return CartWithItemsToJSONTyped(json, false);
}

export function CartWithItemsToJSONTyped(value?: Omit<CartWithItems, 'id'|'UserId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartItems': value['cartItems'] == null ? undefined : ((value['cartItems'] as Array<any>).map(CartItemToJSON)),
    };
}

