/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Category Model
 * @export
 */
export const Category = {
    Ortofrutta: 'ORTOFRUTTA',
    Surgelati: 'SURGELATI',
    Banco: 'BANCO',
    Elettronica: 'ELETTRONICA',
    Casa: 'CASA',
    Surgelati2: 'SURGELATI',
    Liquori: 'LIQUORI'
} as const;
export type Category = typeof Category[keyof typeof Category];


export function instanceOfCategory(value: any): boolean {
    for (const key in Category) {
        if (Object.prototype.hasOwnProperty.call(Category, key)) {
            if (Category[key as keyof typeof Category] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    return json as Category;
}

export function CategoryToJSON(value?: Category | null): any {
    return value as any;
}

export function CategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): Category {
    return value as Category;
}

