/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * ID univoco dell'elemento dell'ordine.
     * @type {number}
     * @memberof OrderItem
     */
    readonly id?: number;
    /**
     * ID dell'ordine a cui appartiene l'elemento.
     * @type {number}
     * @memberof OrderItem
     */
    readonly orderId?: number;
    /**
     * ID del prodotto nell'elemento dell'ordine.
     * @type {number}
     * @memberof OrderItem
     */
    productId: number;
    /**
     * Quantità del prodotto nell'elemento dell'ordine.
     * @type {number}
     * @memberof OrderItem
     */
    quantity: number;
    /**
     * Prezzo unitario del prodotto al momento dell'ordine.
     * @type {number}
     * @memberof OrderItem
     */
    unitPrice: number;
}

/**
 * Check if a given object implements the OrderItem interface.
 */
export function instanceOfOrderItem(value: object): value is OrderItem {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
    return true;
}

export function OrderItemFromJSON(json: any): OrderItem {
    return OrderItemFromJSONTyped(json, false);
}

export function OrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderId': json['OrderId'] == null ? undefined : json['OrderId'],
        'productId': json['ProductId'],
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'],
    };
}

export function OrderItemToJSON(json: any): OrderItem {
    return OrderItemToJSONTyped(json, false);
}

export function OrderItemToJSONTyped(value?: Omit<OrderItem, 'id'|'OrderId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProductId': value['productId'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
    };
}

