/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface OrderWithItems
 */
export interface OrderWithItems {
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof OrderWithItems
     */
    orderItems?: Array<OrderItem>;
    /**
     * ID univoco dell'ordine.
     * @type {number}
     * @memberof OrderWithItems
     */
    readonly id?: number;
    /**
     * ID dell'utente che ha effettuato l'ordine.
     * @type {number}
     * @memberof OrderWithItems
     */
    readonly userId?: number;
    /**
     * Data e ora in cui è stato effettuato l'ordine.
     * @type {Date}
     * @memberof OrderWithItems
     */
    readonly orderDate?: Date;
    /**
     * Importo totale dell'ordine.
     * @type {number}
     * @memberof OrderWithItems
     */
    readonly totalAmount?: number;
    /**
     * Stato attuale dell'ordine.
     * @type {string}
     * @memberof OrderWithItems
     */
    readonly orderStatus?: OrderWithItemsOrderStatusEnum;
    /**
     * Indirizzo di spedizione.
     * @type {string}
     * @memberof OrderWithItems
     */
    shippingAddress: string;
    /**
     * Indirizzo di fatturazione.
     * @type {string}
     * @memberof OrderWithItems
     */
    billingAddress: string;
    /**
     * Metodo di pagamento utilizzato.
     * @type {string}
     * @memberof OrderWithItems
     */
    paymentMethod: string;
    /**
     * ID della transazione di pagamento (se applicabile).
     * @type {string}
     * @memberof OrderWithItems
     */
    readonly transactionId?: string | null;
}


/**
 * @export
 */
export const OrderWithItemsOrderStatusEnum = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Shipped: 'SHIPPED',
    Delivered: 'DELIVERED',
    Cancelled: 'CANCELLED'
} as const;
export type OrderWithItemsOrderStatusEnum = typeof OrderWithItemsOrderStatusEnum[keyof typeof OrderWithItemsOrderStatusEnum];


/**
 * Check if a given object implements the OrderWithItems interface.
 */
export function instanceOfOrderWithItems(value: object): value is OrderWithItems {
    if (!('shippingAddress' in value) || value['shippingAddress'] === undefined) return false;
    if (!('billingAddress' in value) || value['billingAddress'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function OrderWithItemsFromJSON(json: any): OrderWithItems {
    return OrderWithItemsFromJSONTyped(json, false);
}

export function OrderWithItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderWithItems {
    if (json == null) {
        return json;
    }
    return {
        
        'orderItems': json['orderItems'] == null ? undefined : ((json['orderItems'] as Array<any>).map(OrderItemFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'orderDate': json['orderDate'] == null ? undefined : (new Date(json['orderDate'])),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'orderStatus': json['orderStatus'] == null ? undefined : json['orderStatus'],
        'shippingAddress': json['shippingAddress'],
        'billingAddress': json['billingAddress'],
        'paymentMethod': json['paymentMethod'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
    };
}

export function OrderWithItemsToJSON(json: any): OrderWithItems {
    return OrderWithItemsToJSONTyped(json, false);
}

export function OrderWithItemsToJSONTyped(value?: Omit<OrderWithItems, 'id'|'UserId'|'orderDate'|'totalAmount'|'orderStatus'|'transactionId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderItems': value['orderItems'] == null ? undefined : ((value['orderItems'] as Array<any>).map(OrderItemToJSON)),
        'shippingAddress': value['shippingAddress'],
        'billingAddress': value['billingAddress'],
        'paymentMethod': value['paymentMethod'],
    };
}

