/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * ID univoco dell'ordine.
     * @type {number}
     * @memberof Order
     */
    readonly id?: number;
    /**
     * ID dell'utente che ha effettuato l'ordine.
     * @type {number}
     * @memberof Order
     */
    readonly userId?: number;
    /**
     * Data e ora in cui è stato effettuato l'ordine.
     * @type {Date}
     * @memberof Order
     */
    readonly orderDate?: Date;
    /**
     * Importo totale dell'ordine.
     * @type {number}
     * @memberof Order
     */
    readonly totalAmount?: number;
    /**
     * Stato attuale dell'ordine.
     * @type {string}
     * @memberof Order
     */
    readonly orderStatus?: OrderOrderStatusEnum;
    /**
     * Indirizzo di spedizione.
     * @type {string}
     * @memberof Order
     */
    shippingAddress: string;
    /**
     * Indirizzo di fatturazione.
     * @type {string}
     * @memberof Order
     */
    billingAddress: string;
    /**
     * Metodo di pagamento utilizzato.
     * @type {string}
     * @memberof Order
     */
    paymentMethod: string;
    /**
     * ID della transazione di pagamento (se applicabile).
     * @type {string}
     * @memberof Order
     */
    readonly transactionId?: string | null;
}


/**
 * @export
 */
export const OrderOrderStatusEnum = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Shipped: 'SHIPPED',
    Delivered: 'DELIVERED',
    Cancelled: 'CANCELLED'
} as const;
export type OrderOrderStatusEnum = typeof OrderOrderStatusEnum[keyof typeof OrderOrderStatusEnum];


/**
 * Check if a given object implements the Order interface.
 */
export function instanceOfOrder(value: object): value is Order {
    if (!('shippingAddress' in value) || value['shippingAddress'] === undefined) return false;
    if (!('billingAddress' in value) || value['billingAddress'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'orderDate': json['orderDate'] == null ? undefined : (new Date(json['orderDate'])),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'orderStatus': json['orderStatus'] == null ? undefined : json['orderStatus'],
        'shippingAddress': json['shippingAddress'],
        'billingAddress': json['billingAddress'],
        'paymentMethod': json['paymentMethod'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
    };
}

export function OrderToJSON(json: any): Order {
    return OrderToJSONTyped(json, false);
}

export function OrderToJSONTyped(value?: Omit<Order, 'id'|'UserId'|'orderDate'|'totalAmount'|'orderStatus'|'transactionId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shippingAddress': value['shippingAddress'],
        'billingAddress': value['billingAddress'],
        'paymentMethod': value['paymentMethod'],
    };
}

