/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ProductQuantity
 * 
 * @export
 */
export type ProductQuantity = number | string;

export function ProductQuantityFromJSON(json: any): ProductQuantity {
    return ProductQuantityFromJSONTyped(json, false);
}

export function ProductQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductQuantity {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function ProductQuantityToJSON(json: any): any {
    return ProductQuantityToJSONTyped(json, false);
}

export function ProductQuantityToJSONTyped(value?: ProductQuantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

