/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductQuantity } from './ProductQuantity';
import {
    ProductQuantityFromJSON,
    ProductQuantityFromJSONTyped,
    ProductQuantityToJSON,
    ProductQuantityToJSONTyped,
} from './ProductQuantity';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';
import type { ProductPrice } from './ProductPrice';
import {
    ProductPriceFromJSON,
    ProductPriceFromJSONTyped,
    ProductPriceToJSON,
    ProductPriceToJSONTyped,
} from './ProductPrice';

/**
 * Product Model
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    pDescription: string;
    /**
     * 
     * @type {Category}
     * @memberof Product
     */
    category: Category;
    /**
     * 
     * @type {ProductPrice}
     * @memberof Product
     */
    price: ProductPrice;
    /**
     * 
     * @type {ProductQuantity}
     * @memberof Product
     */
    quantity: ProductQuantity;
}



/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('pDescription' in value) || value['pDescription'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'pDescription': json['pDescription'],
        'category': CategoryFromJSON(json['category']),
        'price': ProductPriceFromJSON(json['price']),
        'quantity': ProductQuantityFromJSON(json['quantity']),
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'pDescription': value['pDescription'],
        'category': CategoryToJSON(value['category']),
        'price': ProductPriceToJSON(value['price']),
        'quantity': ProductQuantityToJSON(value['quantity']),
    };
}

