/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductQuantity } from './ProductQuantity';
import {
    ProductQuantityFromJSON,
    ProductQuantityFromJSONTyped,
    ProductQuantityToJSON,
    ProductQuantityToJSONTyped,
} from './ProductQuantity';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';
import type { ProductPrice } from './ProductPrice';
import {
    ProductPriceFromJSON,
    ProductPriceFromJSONTyped,
    ProductPriceToJSON,
    ProductPriceToJSONTyped,
} from './ProductPrice';

/**
 * Product Model Output
 * @export
 * @interface ProductOutput
 */
export interface ProductOutput {
    /**
     * 
     * @type {number}
     * @memberof ProductOutput
     */
    id: number;
    /**
     * Image path for the product
     * @type {string}
     * @memberof ProductOutput
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    pDescription: string;
    /**
     * 
     * @type {Category}
     * @memberof ProductOutput
     */
    category: Category;
    /**
     * 
     * @type {ProductPrice}
     * @memberof ProductOutput
     */
    price: ProductPrice;
    /**
     * 
     * @type {ProductQuantity}
     * @memberof ProductOutput
     */
    quantity: ProductQuantity;
}



/**
 * Check if a given object implements the ProductOutput interface.
 */
export function instanceOfProductOutput(value: object): value is ProductOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('pDescription' in value) || value['pDescription'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function ProductOutputFromJSON(json: any): ProductOutput {
    return ProductOutputFromJSONTyped(json, false);
}

export function ProductOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'imageUrl': json['imageUrl'],
        'title': json['title'],
        'pDescription': json['pDescription'],
        'category': CategoryFromJSON(json['category']),
        'price': ProductPriceFromJSON(json['price']),
        'quantity': ProductQuantityFromJSON(json['quantity']),
    };
}

export function ProductOutputToJSON(json: any): ProductOutput {
    return ProductOutputToJSONTyped(json, false);
}

export function ProductOutputToJSONTyped(value?: ProductOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'imageUrl': value['imageUrl'],
        'title': value['title'],
        'pDescription': value['pDescription'],
        'category': CategoryToJSON(value['category']),
        'price': ProductPriceToJSON(value['price']),
        'quantity': ProductQuantityToJSON(value['quantity']),
    };
}

