/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';

/**
 * 
 * @export
 * @interface UpdateOrderStatusRequest
 */
export interface UpdateOrderStatusRequest {
    /**
     * 
     * @type {OrderStatus}
     * @memberof UpdateOrderStatusRequest
     */
    orderStatus: OrderStatus;
}



/**
 * Check if a given object implements the UpdateOrderStatusRequest interface.
 */
export function instanceOfUpdateOrderStatusRequest(value: object): value is UpdateOrderStatusRequest {
    if (!('orderStatus' in value) || value['orderStatus'] === undefined) return false;
    return true;
}

export function UpdateOrderStatusRequestFromJSON(json: any): UpdateOrderStatusRequest {
    return UpdateOrderStatusRequestFromJSONTyped(json, false);
}

export function UpdateOrderStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderStatus': OrderStatusFromJSON(json['orderStatus']),
    };
}

export function UpdateOrderStatusRequestToJSON(json: any): UpdateOrderStatusRequest {
    return UpdateOrderStatusRequestToJSONTyped(json, false);
}

export function UpdateOrderStatusRequestToJSONTyped(value?: UpdateOrderStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderStatus': OrderStatusToJSON(value['orderStatus']),
    };
}

