/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCartItemQuantityRequest
 */
export interface UpdateCartItemQuantityRequest {
    /**
     * Nuova quantità.
     * @type {number}
     * @memberof UpdateCartItemQuantityRequest
     */
    quantity: number;
}

/**
 * Check if a given object implements the UpdateCartItemQuantityRequest interface.
 */
export function instanceOfUpdateCartItemQuantityRequest(value: object): value is UpdateCartItemQuantityRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function UpdateCartItemQuantityRequestFromJSON(json: any): UpdateCartItemQuantityRequest {
    return UpdateCartItemQuantityRequestFromJSONTyped(json, false);
}

export function UpdateCartItemQuantityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCartItemQuantityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
    };
}

export function UpdateCartItemQuantityRequestToJSON(json: any): UpdateCartItemQuantityRequest {
    return UpdateCartItemQuantityRequestToJSONTyped(json, false);
}

export function UpdateCartItemQuantityRequestToJSONTyped(value?: UpdateCartItemQuantityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
    };
}

