/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';

/**
 * User Model Input
 * @export
 * @interface UserInput
 */
export interface UserInput {
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    password: string;
    /**
     * 
     * @type {UserRole}
     * @memberof UserInput
     */
    userRole?: UserRole;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInput
     */
    address?: string;
}



/**
 * Check if a given object implements the UserInput interface.
 */
export function instanceOfUserInput(value: object): value is UserInput {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserInputFromJSON(json: any): UserInput {
    return UserInputFromJSONTyped(json, false);
}

export function UserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInput {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'userRole': json['userRole'] == null ? undefined : UserRoleFromJSON(json['userRole']),
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function UserInputToJSON(json: any): UserInput {
    return UserInputToJSONTyped(json, false);
}

export function UserInputToJSONTyped(value?: UserInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'userRole': UserRoleToJSON(value['userRole']),
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'phone': value['phone'],
        'address': value['address'],
    };
}

