/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User Model Output
 * @export
 * @interface UserOutput
 */
export interface UserOutput {
    /**
     * 
     * @type {number}
     * @memberof UserOutput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutput
     */
    address?: string;
}

/**
 * Check if a given object implements the UserOutput interface.
 */
export function instanceOfUserOutput(value: object): value is UserOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserOutputFromJSON(json: any): UserOutput {
    return UserOutputFromJSONTyped(json, false);
}

export function UserOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'token': json['token'] == null ? undefined : json['token'],
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function UserOutputToJSON(json: any): UserOutput {
    return UserOutputToJSONTyped(json, false);
}

export function UserOutputToJSONTyped(value?: UserOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'token': value['token'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'phone': value['phone'],
        'address': value['address'],
    };
}

