/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"Design first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User Model for registration
 * @export
 * @interface UserRegister
 */
export interface UserRegister {
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    address?: string;
}

/**
 * Check if a given object implements the UserRegister interface.
 */
export function instanceOfUserRegister(value: object): value is UserRegister {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserRegisterFromJSON(json: any): UserRegister {
    return UserRegisterFromJSONTyped(json, false);
}

export function UserRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegister {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function UserRegisterToJSON(json: any): UserRegister {
    return UserRegisterToJSONTyped(json, false);
}

export function UserRegisterToJSONTyped(value?: UserRegister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'phone': value['phone'],
        'address': value['address'],
    };
}

