/* tslint:disable */
/* eslint-disable */
/**
 * On-Line Shop | Sistemi Web
 * Back-End per lo store- progetto Sistemi web  Approccio \"API first\" per favorire la divisione di ruoli tra back-end e front-end  Link utili: - [Repository progetto](https://github.com/marco-villa-unibo/progetto_sistemi_web)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marco.villa13@studio.unibo.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User Role Model
 * @export
 */
export const UserRole = {
    Customer: 'CUSTOMER',
    Employee: 'EMPLOYEE',
    Admin: 'ADMIN'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];


export function instanceOfUserRole(value: any): boolean {
    for (const key in UserRole) {
        if (Object.prototype.hasOwnProperty.call(UserRole, key)) {
            if (UserRole[key as keyof typeof UserRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserRoleFromJSON(json: any): UserRole {
    return UserRoleFromJSONTyped(json, false);
}

export function UserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRole {
    return json as UserRole;
}

export function UserRoleToJSON(value?: UserRole | null): any {
    return value as any;
}

export function UserRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): UserRole {
    return value as UserRole;
}

